# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: VMWare or EC2 Auto Deploy (CI/CD)

on:
  push:
    branches: [main]


jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: cp .env.stage.example .env

      - run: npm install -g yarn
      - run: yarn
        # This is nest start command, don't misread about development mode. It's ready at production mode1
      - run: yarn build
